[build]
  base = "frontend"
  command = "npm ci && npm run build"
  # o plugin do Next cuida do publish e gera ".netlify/static"
  publish = ".netlify/static"

[[plugins]]
  package = "@netlify/next-runtime"
